name: Check ILovePDF API Status with PDF Conversion

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  check-ilovepdf-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: '22' 

    - name: Install iLovePDF Node.js library
      run: |
        npm install @ilovepdf/ilovepdf-nodejs

    - name: Check API Status with Conversion
      run: |
          node ./src/utils/ilovepdf_check.js --publicKey ${{ secrets.ILOVE_PDF_PUBLIC_KEY }} --secretKey ${{ secrets.ILOVE_PDF_SECRET_KEY }} --check-api
      continue-on-error: false  # Fail the job if API check fails
  
    - name: Handle Failure
      if: failure()
      run: |
          echo "API is down or out of points. Exiting."