name: Check iLovePDF API Status with PDF Conversion

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  check-ilovepdf-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install  dependencies
      run: |
        npm i @ilovepdf/ilovepdf-nodejs minimist
    - name: List directory (for debugging)
      run: ls -R /home/runner/work/next_leoni/next_leoni/public

    - name: Check API Status with Conversion
      id: check_api
      run: |
        node ./src/utils/ilovepdf_check.js --publicKey ${{secrets.ILOVE_PDF_PUBLIC_KEY}} --secretKey ${{secrets.ILOVE_PDF_SECRET_KEY}} --check-api

    - name: Handle Failure
      if: failure()
      run: |
        echo "API is down or out of points. Exiting."
        exit 1  # Ensure the job fails with exit code 1

    - name: Notify on Success
      if: success()
      run: |
        echo "iLovePDF API is operational and conversion successful."
