name: Check ILovePDF API Status

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  check-ilovepdf-api:
    runs-on: ubuntu-latest

    steps:
    - name: Check ILovePDF API Status
      run: |
        # Access API keys securely (replace with your method)
        API_KEY=${{ secrets.ILOVE_PDF_PUBLIC_KEY }}
        API_SECRET=${{ secrets.ILOVE_PDF_SECRET_KEY }}

        response=$(curl -s -o /dev/null -w "%{http_code}" \
          -X POST "https://api.ilovepdf.com/v1/auth" \
          -H "Content-Type: application/json" \
          -d "{\"public_key\":\"$API_KEY\"}")

        if [ "$response" -eq 200 ]; then
          echo "ILovePDF API is operational."
        else
          echo "API might be down or invalid credentials. Status code: $response"
          exit 1
        fi