name: Multi-Repo CI Workflow

on:

    
  push:  
    branches:
      secondary    
  workflow_dispatch:
    inputs:
      node_version: 
        default: '22'
        type: choice
        options:
          - 20
          - 21
          - 22



jobs:
  call-reusable-workflow:
    uses: "./.github/workflows/reusable-main.yml"
    with:
      node_version: ${{inputs.node_version || '22'}} 
  print-use_node_version:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Version used
        run: echo "version used is ${{needs.call-reusable-workflow.outputs.used_node_version}}"
  
