name: Multi-Repo CI Workflow

on:
  push:
  workflow_dispatch:
    inputs:
      node_version: 
        default: '20'
        type: choice
        options:
          - 18
          - 19
          - 20



jobs:
  call-reusable-workflow:
    uses: "./.github/workflows/reusable-main.yml"
    with:
      node_version: ${{inputs.node_version}}

  print-version:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Print Node.js version
        run: echo "Node.js version is ${{ needs.call-reusable-workflow.outputs.node_version }}"
