name: Multi-Repo CI Workflow

on:
  push:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: "./.github/workflows/reusable-main.yml"
    with:
      node_version: '22'

  print-version:
    runs-on: ubuntu-latest
    needs: call-reusable-workflow
    steps:
      - name: Print Node.js version
        run: echo "Node.js version is ${{ needs.call-reusable-workflow.outputs.node_version}}"
