name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/common-setup.yml
    with:
      node-version: '18'
    secrets: inherit
    steps:
      - name: Run linting
        run: npm run lint

  build:
    needs: lint
    uses: ./.github/workflows/common-setup.yml
    with:
      node-version: '18'
    secrets: inherit
    steps:
      - name: Build project
        run: npm run build

  deploy:
    needs: build
    uses: ./.github/workflows/common-setup.yml
    with:
      node-version: '18'
    secrets: inherit
    steps:
      - name: Deploy
        run: npm run deploy
