name: Build and Cache Workflow

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to use'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      # Cache node_modules to speed up installation
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-deps-${{ inputs.node_version }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-deps-${{ inputs.node_version }}
          enableCrossOsArchive: true

      # Install dependencies only if not cached
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      # Cache the .next directory to speed up Next.js builds
      - name: Cache Next.js build output
        id: cache-next
        uses: actions/cache@v4
        with:
          path: .next
          key: nextjs-build-${{ inputs.node_version }}-${{ hashFiles('package.json', 'package-lock.json', 'next.config.js') }}
          restore-keys: |
            nextjs-build-${{ inputs.node_version }}
          enableCrossOsArchive: true
          fail-on-cache-miss: false

      # Build the project
      - name: Build project
        run: npm run build
