name: Cypress End-to-End Tests

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      CYPRESS_baseUrl: 'http://localhost:3000'
      NODE_ENV: test
      


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache
            node_modules
          key: node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-

      - name: Install dependencies
        run: npm ci

      - name: Cache Cypress dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-

      - name: Build the Application
        run: npm run build
      - name: Start Application
        run: npm start &
        env:
          PORT: 3000
      - name: Wait for Application to be Ready
        run: |
            echo "Waiting for application to be ready..."
            while ! curl -s http://localhost:3000 > /dev/null; do
              sleep 5
            done
  
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
     
          

      - name: Upload Cypress test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results  # Path where Cypress stores test results

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots  # Path where Cypress stores screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos  # Path where Cypress stores videos
