name: E2E Test Workflow with Cypress

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

    steps:
      # Checkout the latest code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Cache Node.js modules to speed up installation
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.cache
            node_modules
          key: node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-

      # Install dependencies only if not cached
      - name: Install dependencies
        run: npm ci

      # Cache Cypress dependencies to speed up Cypress installs
      - name: Cache Cypress dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-

      # Build the application
      - name: Build the Application
        run: npm run build

      # Start the application with Cypress
      - name: Start Application with Cypress
        run: |
          CYPRESS=true npm start &
        env:
          PORT: 3000

      # Wait for the application to be ready
      - name: Wait for Application to be Ready
        run: |
          echo "Waiting for application to be ready..."
          while ! curl -s http://localhost:3000 > /dev/null; do
            sleep 5
          done

      # Run Cypress tests using the Cypress GitHub Action
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      # Upload Cypress test results as artifacts
      - name: Upload Cypress test results
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results

      # Upload Cypress screenshots as artifacts
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      # Upload Cypress videos as artifacts
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
