name: Main CI Workflow

on:
  workflow_call:
    inputs:
      node_version:
        description: 'Node.js version to use'
        required: true
        default: '20'
        type: string
      run_tests:
        description: 'Whether to run tests'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          key: node-deps-${{ hashFiles('package-lock.json') }}
          path: node_modules
          enableCrossOsArchive: true

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        if: ${{ inputs.run_tests }}
        run: npm test

      - name: Build project
        run: npm run build

      - name: Get Node.js version
        id: node_version
        run: echo "node_version=${{inputs.node_version}}" >> $GITHUB_OUTPUT

    outputs:
      node_version: ${{ steps.node_version.outputs.node_version }}
